// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgBoyYKCzvGkfb8aBh10tkVRFgoTalxJ4',
    appId: '1:340894688948:web:36abdfc76277e5078ed9e1',
    messagingSenderId: '340894688948',
    projectId: 'upr-housing',
    authDomain: 'upr-housing.firebaseapp.com',
    storageBucket: 'upr-housing.firebasestorage.app',
    measurementId: 'G-88X09L660Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJ-o2AE8zjQYm65aOk7p29AihAPQi1U0',
    appId: '1:340894688948:android:194b09932af9d4b28ed9e1',
    messagingSenderId: '340894688948',
    projectId: 'upr-housing',
    storageBucket: 'upr-housing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtZZWLL9-UDVZPQNG3Zsy3iGDkBlr-kI',
    appId: '1:340894688948:ios:b39479c59ea054858ed9e1',
    messagingSenderId: '340894688948',
    projectId: 'upr-housing',
    storageBucket: 'upr-housing.firebasestorage.app',
    iosBundleId: 'com.example.tutorialPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtZZWLL9-UDVZPQNG3Zsy3iGDkBlr-kI',
    appId: '1:340894688948:ios:b39479c59ea054858ed9e1',
    messagingSenderId: '340894688948',
    projectId: 'upr-housing',
    storageBucket: 'upr-housing.firebasestorage.app',
    iosBundleId: 'com.example.tutorialPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgBoyYKCzvGkfb8aBh10tkVRFgoTalxJ4',
    appId: '1:340894688948:web:043ddb05f52dcfe98ed9e1',
    messagingSenderId: '340894688948',
    projectId: 'upr-housing',
    authDomain: 'upr-housing.firebaseapp.com',
    storageBucket: 'upr-housing.firebasestorage.app',
    measurementId: 'G-HEK76L09G3',
  );

}